version: "3"

services:
  db:
    image: postgres:12
    env_file: .env
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    env_file: .env
    command: /start
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db