# Generated by Django 3.1 on 2021-05-09 02:09

from django.db import migrations, models
import postcodeGeoApp.postcode.models.coordinates
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.FileField(max_length=150, upload_to=postcodeGeoApp.postcode.models.coordinates.coordinate_file_directory_path)),
            ],
            options={
                'ordering': ('-created_at', '-updated_at'),
                'abstract': False,
            },
        ),
    ]
